/* FOR MYSQL WORKBENCH */ 

#BASE DE DATOS
CREATE DATABASE COMERCIO;
USE COMERCIO;

#TABLAS
CREATE TABLE ARTICULOS (  
ARTICULO_ID INT PRIMARY KEY,
NOMBRE VARCHAR(20),  
PRECIO DOUBLE,  
STOCK INT
);

CREATE TABLE FACTURAS (  
FECHA DATE,
LUGAR VARCHAR (30),
LETRA CHAR,
NUMERO INT,
CLIENTE_ID INT,  
ARTICULO_ID INT,  
MONTO DOUBLE,

PRIMARY KEY(LETRA, NUMERO)
);

CREATE TABLE CLIENTES (  
CLIENTE_ID INT PRIMARY KEY,
NOMBRES VARCHAR(20),  
APELLIDOS VARCHAR(25),  
CUIT CHAR(15),  
DIRECCION VARCHAR(30),  
COMENTARIOS VARCHAR(50)
);

#VISUALIZACION
SHOW DATABASES;
SHOW TABLES;
SELECT * FROM CLIENTES;
