
#ORDER BY

SELECT Nombre, Ciudad, Pais FROM CLIENTES_PIZZA  
ORDER BY Pais, LIMIT 50, OFFSET 10;

SELECT Nombre, Pais FROM CLIENTES_PIZZA 
ORDER BY Nombre ASC;

SELECT Nombre, Pais FROM CLIENTES_PIZZA 
ORDER BY Nombre DESC;

SELECT * FROM CLIENTES_PIZZA 
WHERE Cliente_ID = 100 or Cliente_ID = 500
AND Edad > 70
ORDER BY Pais DESC, Nombre ASC;
